### PR TITLE
UI : create landing Page UI

### PR DESCRIPTION
**Pull request by IsmailZhaf**
Sudah selesai membuat UI untuk landing page, dan menambahkan warna background pada body di global css

### CODE REVIEW

**Review by indrazm — APPROVED** [review]
lgtm

**Comment by indrazm** [comment]
@AmruTheSeeker you can merge this.

**Comment by AmruTheSeeker** [comment]
Ok, successfully merged and closed

**Review by AmruTheSeeker — COMMENTED** [review]
Wonderful job mas @IsmailZhaf

**Pull request merged**
